spring:
  web:
    locale: en_EN
    locale-resolver: fixed
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5433/bankdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true